<a href="https://colab.research.google.com/github/boradenihal15-beep/Python-libraries/blob/main/Pandas/Multindexiing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Multiindex series and dataframe**

In [1]:
import pandas as pd
import numpy as np

a series is a 1D and dataframe is 2D.

*   series contains only  values with index whereas dataframe contains multiple rows with multiple conlumns.
*   as in series we required one paramter to fatech as value that is its index and dataframe requires two parameter i.e row and column

In [ ]:
#Does multi index is supported for series?
indexes=[('cse',2019),('cse',2024),('IT',2023),('IT',2021)]
data=pd.Series([1,2,3,4],index=indexes)

In [ ]:
#Yes we can create mutiindex to series but ther eis a problem
#when me manully or directly creates multiindex to series it is created in tuples so we have to fatech a value using index tupel
data[('cse',2024)]
data['cse'] #this throws error

np.int64(3)

In [ ]:
#Solution using buildin methods (also called as hirarchical indexing)

# 1.from_tuples()

multiindex=pd.MultiIndex.from_tuples(indexes)

#this methods sep the tuple values and treat as two different index
#it contain level (1 for branch,2 for year)
multiindex.levels
multiindex.levels[0]

# 2.from product
product=pd.MultiIndex.from_product([['cse','IT'],[2012,2013,2024,2025]])
#similar as from tuple but not requires tuple it 1st list each value to 2nd list each value (cross product)

In [ ]:
#creating series of multiindex
s=pd.Series([1,2,3,4],index=multiindex)
# using product
p=pd.Series([1,2,3,4,5,6,7,8],index=product)

In [ ]:
# how to fetch data using index
print(s['cse'])
print(s['cse',2019])
#using product
print(p['cse'])
print(p['cse',2024])

2019    1
2024    2
dtype: int64
1
2012    1
2013    2
2024    3
2025    4
dtype: int64
3

Now the multiindex is 2D as we need to pass 2 parameter to fetch a single value

So rather thhan making this multindex series it is better to create a dataframe of it

In [ ]:
#unstack
s.unstack()
p.unstack()
# converts the multiindex series to dataframe

     2012  2013  2024  2025
IT      5     6     7     8
cse     1     2     3     4

Therefore the use of making multiindex series is to create a highdim data in lowerdim data
as we make the 2D Data in series
as also we can convert 3D data to 2D
that is the power of series and dataframe

# Multiindex Dataframe


*   A data which contains two indexes and multiple columns are called as 3D data
*   basically a 3D data requires 3 input (2 index and 1 column) to extract a perticular value

example:

  indexes : branch, year

  columns : marks, pkg

so in above table it requires 3 input branch?, year?, what we want (marks/pkg)?

In [4]:
Multiindex_data= pd.MultiIndex.from_product([['cse','IT'],[2020,2019]])

data=pd.DataFrame(data=[[90,5],[50,10],[70,5],[30,2]],index=Multiindex_data,columns=['marks','pkg'])

data

          marks  pkg
cse 2020     90    5
    2019     50   10
IT  2020     70    5
    2019     30    2