<a href="https://colab.research.google.com/github/boradenihal15-beep/Python-libraries/blob/main/Pandas/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import pandas as pd

In [ ]:
marks=[10,20,30]
roll=[11,22,33]
students=['marks']

result=pd.Series(data=marks,index=roll,name='marks of students')
result=pd.DataFrame(marks,roll,students)
result

11    10
22    20
33    30
Name: marks of students, dtype: int64

In [ ]:
names=[1,2,3]
result=pd.Series(names)
print(result.dtype)

int64

In [65]:
data=pd.read_csv('subs.csv')
subs=pd.Series(data['Subscribers gained'])

In [ ]:
data=pd.read_csv('kohli_ipl.csv')
s=pd.Series(data=data['runs'],index=data['match_no'])
s

match_no
1      23.0
2      13.0
3      12.0
4       1.0
5       9.0
       ...
211    20.0
212    73.0
213    25.0
214     7.0
215     NaN
Name: runs, Length: 215, dtype: float64

In [23]:
data = pd.read_csv('bollywood.csv')
s=data['lead'].squeeze()
s.value_counts()

lead
Akshay Kumar         48
Amitabh Bachchan     45
Ajay Devgn           38
Salman Khan          31
Sanjay Dutt          26
                     ..
Seema Azmi            1
Akanksha Puri         1
Charanpreet Insan     1
Jaideep Ahlawat       1
Monali Thakur         1
Name: count, Length: 566, dtype: int64

In [56]:
data=pd.read_csv('kohli_ipl.csv')
vk=pd.Series(data=data['runs'],index=data['match_no'])
print(vk)
vk.sort_values(ascending=False)
print(vk)

match_no
1      23.0
2      13.0
3      12.0
4       1.0
5       9.0
       ...
211    20.0
212    73.0
213    25.0
214     7.0
215     NaN
Name: runs, Length: 215, dtype: float64
match_no
1      23.0
2      13.0
3      12.0
4       1.0
5       9.0
       ...
211    20.0
212    73.0
213    25.0
214     7.0
215     NaN
Name: runs, Length: 215, dtype: float64

In [64]:
vk.shape #considers null values
vk.count() # do not considers null values

data['runs'].sum()
data['runs'].count()

np.int64(215)

In [68]:
subs.sum()
subs.

np.int64(0)

In [81]:
vk[[1,3,5]]

match_no
1    23.0
3    12.0
5     9.0
Name: runs, dtype: float64

In [89]:
l1=[1,3,4,2,5]
sorted(l1)

[1, 2, 3, 4, 5]

In [139]:
data=pd.read_csv('bollywood.csv')
movies=data['lead'].squeeze()
count=movies.value_counts()
count[count>20]

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
Shah Rukh Khan      22
Emraan Hashmi       21
Name: count, dtype: int64